# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dc0ed9f5266b916bd6d7d4cabbf3edd311df50cde6b431c598cf64ed6a95b43ac25d656eafacfe837cda6e9fae9d103251de3319d841eb928cbf42dc98d53aa

test:
  secret_key_base: 0fac88a19328958c25641c8746f2f48d85ef713540311e32744c842416d69a7f95f7b132834ee0ccc676551e863af66ab7b08e340d1c0debd090bbbb77480038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
